[package]
name = "rsql"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = { version = "0.11.0", features = ["history"] }
dotenvy = "0.15.7"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.41.0", features = ["full"] }
prettytable-rs = "^0.10"
